Repository masumi-network/sokosumi, pull requests merged in 2025-04, with the labels that each got.

#319 refactor(db): centralize types and standardize credit handling
  web-app/prisma/seed.ts
  web-app/src/app/(landing)/agents/components/featured-agent.tsx
  web-app/src/app/(landing)/agents/page.tsx
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/create-job-section.tsx
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/header.tsx
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-columns.tsx
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-detail-section.tsx
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details.tsx
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/jobs-table.tsx
  web-app/src/app/app/agents/components/filtered-agents.tsx
  web-app/src/app/app/agents/page.tsx
  web-app/src/app/app/components/user-credits.tsx
  web-app/src/components/agents/agent-bookmark-button.tsx
  web-app/src/components/agents/agent-card.tsx
  web-app/src/components/agents/agent-detail.tsx
  web-app/src/components/agents/agents.tsx
  web-app/src/components/breadcrumb-navigation/breadcrumb-navigation.client.tsx
  web-app/src/lib/actions/job.actions.ts
  web-app/src/lib/db/services/agent.service.ts
  web-app/src/lib/db/services/agentList.service.ts
  web-app/src/lib/db/services/credit.service.ts
  web-app/src/lib/db/services/job.service.ts
  web-app/src/lib/db/services/tag.service.ts
  web-app/src/lib/db/services/user.service.ts
  web-app/src/lib/db/types/agent.types.ts
  web-app/src/lib/db/types/agentList.types.ts
  web-app/src/lib/db/types/job.types.ts
  web-app/src/lib/db/utils/credit.utils.ts
Labels: technical enhancement

#345 fix(stripe): Conditionally set customer or customer_email in checkout session
  web-app/src/lib/actions/stripe.actions.ts
Labels: bug

#350 fix(job): adjust timeout settings for job start operation
  web-app/src/lib/db/services/job.service.ts
Labels: bug

#351 fix(db): add default role field to seed user
  web-app/prisma/seed.ts
Labels: bug

#353 fix(agent): Add agent tags and refactor query state management
  web-app/package.json
  web-app/pnpm-lock.yaml
  web-app/src/app/api/cron/registry-sync/route.ts
  web-app/src/app/app/agents/components/filter-section.tsx
  web-app/src/app/app/agents/components/filtered-agents.tsx
  web-app/src/app/app/agents/components/use-gallery-filter.ts
  web-app/src/app/layout.tsx
  web-app/src/config/env.config.ts
Labels: bug

#364 fix(theme): remove close button and refine tag styles
  web-app/src/app/(landing)/(auth)/components/close-button.tsx
  web-app/src/app/app/agents/components/tags.tsx
Labels: bug, user interface

#375 chore: update packageManager version to pnpm@10.8.1
  job-cron-caller/package.json
  package.json
  registry-cron-caller/package.json
  web-app/package.json
Labels: javascript

#377 fix(user-avatar): update logout terminology to 'signOut'
  web-app/src/app/app/components/user-avatar/user-avatar.client.tsx
Labels: bug, user interface

#386 fix(auth): update redirect paths from '/signin' to '/login'
  web-app/src/app/(landing)/(auth)/forgot-password/components/form.tsx
  web-app/src/app/(landing)/(auth)/reset-password/components/form.tsx
  web-app/src/app/(landing)/(auth)/reset-password/page.tsx
  web-app/src/app/(landing)/components/auth-buttons.tsx
  web-app/src/lib/auth/utils.ts
  web-app/src/middleware/authorization.ts
Labels: bug

#378 feat(credits): add fee calculation and tracking to credit cost logic
  web-app/.vscode/cspell.json
  web-app/src/lib/db/services/credit.service.ts
  web-app/src/lib/db/services/job.service.ts
Labels: database

#387 chore(auth): remove unused plugins from Better-Auth integration
  web-app/.vscode/cspell.json
  web-app/prisma/migrations/20250415063105_init/migration.sql
  web-app/prisma/schema.prisma
  web-app/prisma/seed.ts
  web-app/src/lib/auth/auth.client.ts
  web-app/src/lib/auth/auth.ts
  web-app/src/middleware.ts
  web-app/src/middleware/authorization.ts
Labels: database

#393 feat(jobs): show localized error when balance is insufficient to start a job
  web-app/messages/en.json
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-input/job-inputs-form.client.tsx
  web-app/src/lib/actions/job.actions.ts
Labels: user experience

#398 refactor(credits): unify agent credit pricing API and migrate to cents-based model
  web-app/prisma/migrations/20250416071644_init/migration.sql
  web-app/prisma/schema.prisma
  web-app/prisma/seed.ts
  web-app/src/app/(landing)/agents/[agentId]/page.tsx
  web-app/src/app/(landing)/agents/page.tsx
  web-app/src/app/(landing)/components/agents-gallery.tsx
  web-app/src/app/api/cron/registry-sync/route.ts
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/create-job-section.tsx
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-input/job-inputs-form.client.tsx
  web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-input/job-inputs-form.tsx
  web-app/src/app/app/agents/[agentId]/jobs/@right/page.tsx
  web-app/src/app/app/agents/[agentId]/jobs/components/header.tsx
  web-app/src/app/app/agents/[agentId]/jobs/layout.tsx
  web-app/src/app/app/agents/[agentId]/page.tsx
  web-app/src/app/app/agents/components/filtered-agents.tsx
  web-app/src/app/app/agents/page.tsx
  web-app/src/app/app/billing/page.tsx
  web-app/src/app/app/components/user-credits.tsx
  web-app/src/components/agents/agent-card.tsx
  web-app/src/components/agents/agent-detail.tsx
  web-app/src/components/agents/agents.tsx
  web-app/src/components/billing/billing-form.tsx
  web-app/src/lib/actions/job.actions.ts
  web-app/src/lib/actions/stripe.actions.ts
  web-app/src/lib/db/services/credit.service.ts
  web-app/src/lib/db/services/fiatTransaction.service.ts
  web-app/src/lib/db/services/job.service.ts
  web-app/src/lib/db/types/credit.type.ts
  web-app/src/lib/db/utils/credit.utils.ts
Labels: technical enhancement, database

#403 refactor(landing): refactor hero section with themed kanji logo and layout cleanup ✨
  web-app/messages/en.json
  web-app/public/kanji/sokosumi-black.svg
  web-app/public/kanji/sokosumi-white.svg
  web-app/src/app/(landing)/components/hero.tsx
  web-app/src/app/(landing)/components/search-form.tsx
  web-app/src/app/(landing)/page.tsx
  web-app/src/components/masumi-logos.tsx
Labels: user interface

#404 fix(ui): adjust header background opacity for improved visual clarity ✨
  web-app/src/app/(landing)/components/header.tsx
Labels: user interface

#408 refactor(landing): Number Talks section for i18n and modularity 🌐✨
  web-app/messages/en.json
  web-app/src/app/(landing)/components/number-talks.tsx
Labels: user interface

#413 refactor(logo): update logo SVG files and component references
  web-app/public/kanji/sokosumi-black.svg
  web-app/public/kanji/sokosumi-logo-kanji-black.svg
  web-app/public/kanji/sokosumi-logo-kanji-white.svg
  web-app/public/kanji/sokosumi-white.svg
  web-app/public/logos/kodosumi-logo-black.svg
  web-app/public/logos/kodosumi-logo-white.svg
  web-app/public/logos/masumi-logo-black.svg
  web-app/public/logos/masumi-logo-white.svg
  web-app/public/logos/sokosumi-logo-black.svg
  web-app/public/logos/sokosumi-logo-white.svg
  web-app/src/app/(landing)/components/header.tsx
  web-app/src/app/(landing)/components/how-it-works.tsx
  web-app/src/app/(landing)/components/monetize-your-agent.tsx
  web-app/src/app/(landing)/components/sheet-navigation.tsx
  web-app/src/app/app/components/sidebar/index.tsx
  web-app/src/components/masumi-logos.tsx
Labels: bug, user interface

#464 feat(agents): redesign featured agent component with pricing
  web-app/messages/en.json
  web-app/src/app/(landing)/agents/components/featured-agent.tsx
  web-app/src/app/(landing)/agents/page.tsx
Labels: user interface

#518 feat(credits): enforce minimum fee of 1 credit in cents for credit purchases
  web-app/src/config/env.config.ts
  web-app/src/lib/services/credit/service.ts
Labels: enhancement

#516 feat(database): add dynamic USDM unit seeding and support for multiple networks in credit cost
  web-app/prisma/seed.ts
  web-app/src/lib/utils/index.ts
  web-app/src/lib/utils/usdm-unit.ts
Labels: enhancement, database
